version: '3.8'

services:
  # Frontend React application
  client:
    build:
      context: ./client
      dockerfile: ../docker/Dockerfile.client
    container_name: translation-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - translation-network

  # Backend Node.js application
  server:
    build:
      context: ./server
      dockerfile: ../docker/Dockerfile.server
    container_name: translation-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./translations:/app/translations
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/translation-app
      - JWT_SECRET=your_jwt_secret_change_in_production
      - DEEPL_API_KEY=your_deepl_api_key
      - MS_TRANSLATOR_KEY=your_microsoft_translator_key
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_REGION=us-east-1
      - LIBRE_TRANSLATE_API_URL=http://libretranslate:5000
    depends_on:
      - mongo
      - libretranslate
    networks:
      - translation-network

  # MongoDB database
  mongo:
    image: mongo:latest
    container_name: translation-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - translation-network

  # LibreTranslate service (open source translation API)
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: translation-libretranslate
    ports:
      - "5500:5000"
    environment:
      - LT_LOAD_ONLY=en,es,fr,de,it,pt,ru,zh,ja,ko
    networks:
      - translation-network

  # Redis for caching and job queue
  redis:
    image: redis:alpine
    container_name: translation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - translation-network

volumes:
  mongo-data:
  redis-data:

networks:
  translation-network:
    driver: bridge